[package]
name = "snaploom-platform-windows"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
publish = false

[features]
default = []
tauri-shell = ["dep:tauri", "dep:tauri-plugin-dialog"]
desktop-shell = [
  "tauri-shell",
  "dep:tauri-plugin-autostart",
  "dep:tauri-plugin-global-shortcut",
  "dep:tauri-plugin-notification",
]

[dependencies]
getrandom.workspace = true
snaploom-platform-contract = { path = "../contract", version = "=0.1.0" }
tauri = { workspace = true, optional = true }
tauri-plugin-dialog = { workspace = true, optional = true }
tauri-plugin-autostart = { workspace = true, optional = true }
tauri-plugin-global-shortcut = { workspace = true, optional = true }
tauri-plugin-notification = { workspace = true, optional = true }

[target.'cfg(windows)'.dependencies]
windows-core = "=0.61.2"
windows-link = "=0.1.3"
windows-numerics = "=0.2.0"
windows-result = "=0.3.4"
windows-strings = "=0.4.2"
