<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Snaploom.Platform.Abstractions</AssemblyName>
    <RootNamespace>Snaploom.Platform.Abstractions</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Snaploom.Core/Snaploom.Core.csproj" />
  </ItemGroup>
</Project>
